# Generated by Django 3.0.3 on 2020-04-15 23:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='city',
            field=models.CharField(choices=[(None, 'choice City'), ('Andhra Pradesh', (('mp', 'Madesdsds'),)), ('Arunachal Pradesh', (('as', 'asasasasa'),))], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
