# Generated by Django 3.0.5 on 2020-05-13 14:12

import account.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Full Name Ex.shyam kumar yadav', regex='[A-Za-z]*\\s[A-Za-z]*\\s[A-Za-z]*')], verbose_name='Full Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email ')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Data of Birth')),
                ('contactNo', models.CharField(max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid Phone Number.', regex='^[6-9]\\d{9}$')], verbose_name='Phone Number')),
                ('state', models.CharField(choices=[(None, 'Select State'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CT', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UT', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal'), ('AN', 'Andaman and Nicobar Islands'), ('CH', 'Chandigarh'), ('DB', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('JK', 'Jammu and Kashmir'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('PY', 'Puducherry')], max_length=2, null=True, verbose_name='State')),
                ('city', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid city.', regex='^\\w[A-Za-z ]+$')], verbose_name='City')),
                ('pincode', models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Enter Valid pincode.', regex='^\\d{6}$')], verbose_name='Pincode')),
                ('full_address', models.TextField(max_length=50, null=True, verbose_name='Full Address')),
                ('profile', models.FileField(blank=True, default='Member_Img/default_user.jpg.', upload_to=account.models.upload_to_user, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blp', 'bmp', 'dib', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'apng', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'tif', 'tiff', 'jfif', 'jpe', 'jpg', 'jpeg', 'mpg', 'mpeg', 'mpo', 'msp', 'palm', 'pcd', 'pdf', 'pxr', 'pbm', 'pgm', 'ppm', 'pnm', 'psd', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'icb', 'vda', 'vst', 'webp', 'wmf', 'emf', 'xbm', 'xpm'], message='Select valid Image.')])),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
