# Generated by Django 3.0.6 on 2020-05-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200513_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_defaulter',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
